#!/usr/bin/env ruby
require 'shellwords'
require 'open3'

params = ARGV.to_a
if params[0] == "commit-tree"
  params << "-S"
end

params.unshift("git")

system params.map { |param| Shellwords.escape(param) }.join(" ")
